package report

import (
	"fmt"
	"math"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/moveeeax/rpc-lag-probe/internal/analysis"
)

// chainIDs maps the chains v1 supports to their EVM chain id.
var chainIDs = map[string]int{
	"ethereum": 1,
	"base":     8453,
}

// ERPC renders an eRPC upstream configuration whose thresholds come from the
// measured evidence rather than from a vendor's marketing page.
//
// It is a starting point, not a drop-in: endpoints are emitted as environment
// placeholders because the evidence log deliberately never contains a URL or
// an API key. Review it against the eRPC documentation for the version you run.
func ERPC(r *Result) string {
	var w strings.Builder
	fmt.Fprintf(&w, "# eRPC upstream configuration generated by rpc-lag-probe.\n")
	if !r.Bundle.First.IsZero() {
		fmt.Fprintf(&w, "# Derived from %s of measurement (%s → %s) across %s.\n",
			roundDuration(r.Bundle.Last.Sub(r.Bundle.First)),
			r.Bundle.First.UTC().Format(time.RFC3339), r.Bundle.Last.UTC().Format(time.RFC3339),
			joinOr(r.Bundle.Regions, "one region"))
	}
	fmt.Fprintf(&w, "#\n")
	fmt.Fprintf(&w, "# Endpoint URLs are environment placeholders on purpose: the evidence log\n")
	fmt.Fprintf(&w, "# never contains a provider URL or API key, so this file cannot leak one.\n")
	fmt.Fprintf(&w, "# Review the failsafe values before deploying.\n\n")

	byChain := map[string][]int{}
	for i, s := range r.Summaries {
		byChain[s.Chain] = append(byChain[s.Chain], i)
	}
	chains := make([]string, 0, len(byChain))
	for c := range byChain {
		chains = append(chains, c)
	}
	sort.Strings(chains)

	fmt.Fprintf(&w, "projects:\n  - id: main\n    upstreams:\n")
	if len(r.Summaries) == 0 {
		fmt.Fprintf(&w, "      [] # no endpoints in the evidence log\n")
		return w.String()
	}

	for _, chain := range chains {
		idx := byChain[chain]
		// Rank by lag first, then availability: a fast endpoint serving stale
		// state is worse than a slightly slower one that is current.
		sort.SliceStable(idx, func(a, b int) bool {
			sa, sb := r.Summaries[idx[a]], r.Summaries[idx[b]]
			if sa.LagBlocksP99 != sb.LagBlocksP99 {
				return sa.LagBlocksP99 < sb.LagBlocksP99
			}
			if sa.Availability != sb.Availability {
				return sa.Availability > sb.Availability
			}
			return sa.LatencyP99 < sb.LatencyP99
		})
		for _, i := range idx {
			s := r.Summaries[i]
			writeUpstream(&w, s, chain)
		}
	}
	fmt.Fprintf(&w, "\n# Suggested Prometheus alert thresholds, from the same evidence:\n")
	fmt.Fprintf(&w, "#   rpc_probe_lag_blocks > %d for 1m\n", suggestedLagAlert(r))
	fmt.Fprintf(&w, "#   increase(rpc_probe_divergence_events_total[10m]) > 0\n")
	return w.String()
}

func writeUpstream(w *strings.Builder, s analysis.EndpointSummary, chain string) {
	id := slug(s.Endpoint)
	fmt.Fprintf(w, "      # measured: availability %.2f%%, lag p99 %.0f blocks / %.1fs, latency p99 %s, leader %.1f%% of polls\n",
		s.Availability*100, s.LagBlocksP99, s.LagSecondsP99, roundDuration(s.LatencyP99), s.LeaderShare*100)
	fmt.Fprintf(w, "      - id: %s\n", id)
	fmt.Fprintf(w, "        endpoint: ${%s_URL}\n", envName(s.Endpoint))
	fmt.Fprintf(w, "        type: evm\n")
	fmt.Fprintf(w, "        evm:\n          chainId: %d\n", chainIDs[chain])
	fmt.Fprintf(w, "        failsafe:\n")
	fmt.Fprintf(w, "          timeout:\n            duration: %s\n", timeoutFor(s))
	fmt.Fprintf(w, "          retry:\n            maxAttempts: %d\n            delay: 100ms\n            backoffMaxDelay: 1s\n            backoffFactor: 1.5\n", retriesFor(s))
	if d, ok := hedgeFor(s); ok {
		fmt.Fprintf(w, "          hedge:\n            delay: %s\n            maxCount: 1\n", d)
	}
	fmt.Fprintf(w, "\n")
}

// timeoutFor is twice the measured p99 latency, rounded up to 100ms, clamped
// into a range where the value is still a timeout and not a hang.
func timeoutFor(s analysis.EndpointSummary) string {
	d := 2 * s.LatencyP99
	if d < 1*time.Second {
		d = 1 * time.Second
	}
	if d > 30*time.Second {
		d = 30 * time.Second
	}
	return roundUp(d, 100*time.Millisecond).String()
}

// retriesFor gives a flaky endpoint one extra attempt; a clean one does not
// need it and the retry only costs quota.
func retriesFor(s analysis.EndpointSummary) int {
	switch {
	case s.Availability >= 0.999:
		return 1
	case s.Availability >= 0.99:
		return 2
	default:
		return 3
	}
}

// hedgeFor suggests a hedge delay for endpoints whose tail is far off their
// median. Endpoints with a tight latency distribution get no hedge: it would
// only duplicate paid requests.
func hedgeFor(s analysis.EndpointSummary) (time.Duration, bool) {
	if s.LatencyP50 <= 0 || s.LatencyP99 < 2*s.LatencyP50 {
		return 0, false
	}
	return roundUp(s.LatencyP90, 50*time.Millisecond), true
}

func suggestedLagAlert(r *Result) uint64 {
	worst := 0.0
	for _, s := range r.Summaries {
		if s.LagBlocksP99 > worst {
			worst = s.LagBlocksP99
		}
	}
	n := uint64(math.Ceil(worst)) + 1
	if n < 2 {
		n = 2
	}
	return n
}

func roundUp(d, unit time.Duration) time.Duration {
	if unit <= 0 || d <= 0 {
		return d
	}
	if r := d % unit; r != 0 {
		d += unit - r
	}
	return d
}

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func slug(s string) string {
	out := nonAlnum.ReplaceAllString(strings.ToLower(s), "-")
	return strings.Trim(out, "-")
}

func envName(s string) string {
	return strings.ToUpper(strings.ReplaceAll(slug(s), "-", "_"))
}
